# -*- coding: utf-8 -*-
"""07/02/2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCXYbZkQ0RrTNWl0aR2goOw41Q-TuaAV
"""

X = 4
X1 = 9
X2 = 5

xresult = (((2+5)*3)+X+5)<X1
print(xresult)
xresult = (((2+5)*3)+(X+5+X1)==(X+6+X2*2))
print(xresult)
xresult = (((3*6)+X-3)<X2)
print(xresult)
xresult=(((7*8)>(X+4>X1)<(X*2+X+X2*9)))
print(xresult)

n = 19

xresult = (n >= 20 and n <= 30)
print(xresult)

xresult = (n <= 20 or n >= 30)
print(xresult)

xresult = (n < 20 or not n > 30)
print(xresult)

nota1 = 8
nota2 = 6
media = (nota1 + nota2)/2

if media>=7 :
    print("aprovado")

else:
    print ("reprovado")