# -*- coding: utf-8 -*-
"""08/02/2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15TtuXZ-BHRUZPiYysabZj5bAQHUHtIhV
"""

valor1 = int(input("Digite o valor 1: "))
valor2 = int(input("Digite o valor 2: "))
valort = (valor1 + valor2)

if valort >=15:
  total = (f"Sua compra no total custou:{valort}")
  print(total)

numero = int(input("Digite o número: "))

if numero >0:
  print ("Seu número é positivo")

elif numero <0:
  print ("Seu número é negativo")

else:
  print ("Seu número é neutro")

idade = int(input("Digite sua idade: "))

if idade >= 18:
  print("Você é maior de idade.")

elif idade:
  print("Você é menor de idade")

temperatura = int(input("Digite a temperatura atual: "))

if temperatura >26:
  print("temperatura quente")

elif temperatura <23:
  print("temperatura fria")

else:
  print("temperatura agradável")

numero1 = int(input("Digite o número 1: "))
numero2 = int(input("Digite o número 2: "))


if numero1 == numero2:
  print("Números iguais")

else:
  print("Números diferentes")

usuario = int(input("Digite a sua senha: "))

if usuario == 1234:
  print("ACESSO PERMITIDO")

else:
  print("ACESSO NEGADO")

nota1 = int(input("Digite a nota 1 do aluno: "))
nota2 = int(input("Digete a nota 2 do aluno: "))
media = (nota1 + nota2)/2

if media >= 7:
  print("Aluno aprovado")

elif media <=4:
  print("Aluno reprovado")

else:
  print("Aluno de exame")

time1 = int(input("Digite os gols do primeiro time: "))
time2 = int(input("Digite os gols do segundo time: "))

if time1 == time2:
  print("EMPATE")

elif time1 > time2:
  print("VITORIA DO TIME1!!!")

else:
  print("VITORIA DO TIME2!!!")

turno = input("Digite qual periodo você estuda. M-Matutino, V-Vespertino ou N-Noturno? ")

if turno == "M":
  print("Bom dia, flor do dia!")

elif turno == "V":
  print("Boa tarde, flor do sol!")

elif turno == "N":
  print("Boa noite, flor da noite!")

else:
  print("Valor Inválido")